config/routes.rb
Rails.application.routes.draw do
  get 'posts/answered' => 'posts#answered'
  resources :reactions
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  
  root to: "home#index"
  resources :users do
    resources :notifications, only: :index
  end
  
    resources :posts do
      resources :likes, only: [:create, :destroy]
        resources :answers, shallow: true do
          resources :reactions
  end
end

  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end

  resources :posts, expect: [:index] do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :set_like
    before_action :authenticate_user!

    def create
        @like = current_user.likes.new(post_id: @post.id)
        @like.save
        @likes = Like.where(post_id: @post.id)
        post = Post.find(params[:post_id])
        post.create_notification_like!(current_user)
    end

    def destroy
        @like = Like.find_by(post_id: @post.id, user_id: current_user.id).destroy
        @likes = Like.where(post_id: @post.id)
    end

    private
    def set_like
        @post = Post.find(params[:post_id])
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
    <% if Like.find_by(user_id: current_user.id, post_id: post.id) %>
      <%= link_to post_like_path(post, post.likes), class: "like-link", method: :DELETE, remote: true do %>
      <i class="fa fa-heart unlike-btn"></i>
    <% end %>
    <%= post.likes.count %>
<% else %>
      <%= link_to post_likes_path(post), class: "like-link", method: :POST, remote: true do %>
        <i class="fa fa-heart like-btn"></i>
      <% end %>
      <%= post.likes.count %>
    <% end %>
<% end %>

app/views/likes/create.js.erb
$('#post_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#post_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");