config/routes.rb
Rails.application.routes.draw do
  get 'posts/answered' => 'posts#answered'
  resources :reactions
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  
  root to: "home#index"
  resources :users do
    resources :notifications, only: :index
  end
  
    resources :posts do
      resources :likes, only: [:create, :destroy]
        resources :answers, shallow: true do
          resources :reactions
  end
end

  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end

  resources :posts, expect: [:index] do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :answers, through: :posts
  has_many :likes
  has_many :favorites, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     user_path(resource)
   end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
     user_path(resource)
    end

   def after_update_path_for(resource)
    user_path(resource)
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    favorites = Favorite.where(user_id: current_user.id).pluck(:post_id)
    @favorite_list = Post.find(favorites)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="option first">
    <% if @user.id == current_user.id %> 
        <%= link_to(edit_user_registration_path(@user)) do %>
            <button class="btn btn--orange btn--cubic btn--shadow">プロフィール変更</button>
        <% end %>
</div>
<div class="option">
        <%= link_to(user_notifications_path(current_user)) do %>
            <button class="btn btn--orange btn--cubic btn--shadow">お知らせ</button>
        <% end %>
    <% end %>
</div>

<div class="user-name">
    <h1><%= @user.username %>さんの投稿一覧</h1>
</div>

<% if @user.posts.exists? %>
    <table>
        <tr>
            <th>種目</th>
            <th>動画</th>
            <th>コメント</th>
            <th>オプション</th>
        </tr>
        <tr>
        <% @user.posts.each do |post| %>
            <td class="icon"><% post.tags.each do |tag| %>
                <%= tag.name %>
            <% end %></td>
            <td class="icon"><%= link_to post.video_url.to_s do %>
                <%= video_tag(post.video.to_s, :controls => true, :size => 15*10) %>
            <% end %></td>
            <td class="icon"><%= post.content %>
            <p><%= time_ago_in_words(post.created_at) %>前</p></td>
            <td class="icon"><%= link_to '詳細', post_path(post) %>
            <% if @user.id == current_user.id %>
                <%= link_to '変更', edit_post_path(post) %>
                <%= link_to '削除', post_path(post), method: :delete, data:{ confirm: '削除してもいいですか？' } %>
            <% end %></td>
        </tr>
        <% end %>
    </table>
<% else %>
    <h1 class="not">投稿はありません</h1>
<% end %>

<h1 class="favorite"><%= @user.username %>さんのお気に入り一覧</h1>

<% if @favorite_list.present? %>
    <table class="tbl">
        <tr>
            <th>種目</th>
            <th>動画</th>
            <th>コメント</th>
            <th>オプション</th>
        </tr>
        <tr>
            <% @favorite_list.each do |post| %>
                <td class="icon"><% post.tags.each do |tag| %>
                    <%= tag.name %>
                <% end %></td>
                <td class="icon"><%= link_to post.video_url.to_s do %>
                    <%= video_tag(post.video.to_s, :controls => true, :size => 15*10) %>
                <% end %></td>
                <td class="icon"><%= post.content %>
                <p><%= time_ago_in_words(post.created_at) %>前</p></td>
                <td class="icon"><%= link_to '詳細', post_path(post) %></td>
        </tr>
            <% end %>
    </table>
<% else %>
    <div class="not-favorite">
        <% if @user.id == current_user.id %>
            <h1 class="not">お気に入りはありません</h1>
            <div class="search-favorite">
                <%= link_to posts_path do %>
                    <button class="btn btn--orange btn--cubic btn--shadow">お気に入りを探す</button>
                <% end %>
            </div>
        <% else %>
            <h1 class="exist">お気に入りはありません</h1>
        <% end %>
    </div>
<% end %>