config/routes.rb
Rails.application.routes.draw do
  get 'posts/answered' => 'posts#answered'
  resources :reactions
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  
  root to: "home#index"
  resources :users do
    resources :notifications, only: :index
  end
  
    resources :posts do
      resources :likes, only: [:create, :destroy]
        resources :answers, shallow: true do
          resources :reactions
  end
end

  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end

  resources :posts, expect: [:index] do
    resource :favorites, only: [:create, :destroy]
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_reaction, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @reactions = Reaction.all
  end

  def show
  end

  def new
    answer = Answer.find(params[:answer_id])
    @reaction = answer.reactions.build(user_id: current_user.id)
  end

  def edit
  end

  def create
    answer = Answer.find(params[:answer_id])
    @reaction = answer.reactions.build(reaction_params)
    @post = @reaction.answer.post

    respond_to do |format|
      if @reaction.save
        @post.create_notification_reaction!(current_user, @reaction.id)
        format.html { redirect_to answer.post, notice: "Reaction was successfully created." }
        format.json { render :show, status: :created, location: @reaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reaction.update(reaction_params)
        format.html { redirect_to　@reaction, notice: "Reaction was successfully updated." }
        format.json { render :show, status: :ok, location: @reaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reaction.destroy
    respond_to do |format|
      format.html { redirect_to reactions_url, notice: "Reaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_reaction
      @reaction = Reaction.find(params[:id])
    end

    def reaction_params
      params.require(:reaction).permit(:user_id, :answer_id, :body)
    end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_form.html.erb
<%= form_with(model: @reaction, url: answer_reactions_path(@reaction.answer.id), local: true) do |form| %>
  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="content-form">
    <%= form.text_area :body, class: "comment" %>
  </div>

  <div class="box-signup">
    <%= form.submit "コメントする" %>
  </div>
<% end %>

app/views/reactions/new.html.erb
<div class="box-comment">
    <div class="box-inner">
        <h1>コメント</h1>
        <%= render 'form', reaction: @reaction %>
    </div>
</div>

<div class="back-show">
    <%= link_to(post_path(@reaction.answer.post)) do %>
        <button class="btn btn--orange btn--cubic btn--shadow">戻る</button>
    <% end %>
</div>