config/routes.rb
Rails.application.routes.draw do
  get 'posts/answered' => 'posts#answered'
  resources :reactions
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  
  root to: "home#index"
  resources :users do
    resources :notifications, only: :index
  end
  
    resources :posts do
      resources :likes, only: [:create, :destroy]
        resources :answers, shallow: true do
          resources :reactions
  end
end

  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end

  resources :posts, expect: [:index] do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
    validates :video, presence: true
    validates :content, presence: true, length: { maximum: 140 }
    mount_uploader :video, VideoUploader
    belongs_to :user
    has_many :answers, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
    has_many :notifications, dependent: :destroy

    def create_notification_like!(current_user)
        temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ?", current_user.id, user_id, id, 'like'])
        if temp.blank?
            notification = current_user.active_notifications.new(
                post_id: id,
                visited_id: user_id,
                action: 'like'
            )
            if notification.visitor_id == notification.visited_id
                notification.checked = true
            end
            notification.save if notification.valid?
        end
    end

    def create_notification_reaction!(current_user, reaction_id)
        temp_ids = Reaction.select(:user_id).where(answer_id: id).where.not(user_id: current_user.id).distinct
        temp_ids.each do |temp_id|
            save_notification_reaction!(current_user, reaction_id, temp_id['user_id'])
        end
        save_notification_reaction!(current_user, reaction_id, user_id) if temp_ids.blank?
    end

    def save_notification_reaction!(current_user, reaction_id, visited_id)
        notification = current_user.active_notifications.new(
            post_id: id,
            reaction_id: reaction_id,
            visited_id: visited_id,
            action: 'reaction'
        )
        if notification.visitor_id == notification.visited_id
            notification.checked = true
        end
        notification.save if notification.valid?
    end

    def create_notification_answer!(current_user, answer_id)
        save_notification_answer!(current_user, answer_id, user_id)
    end
    
    def save_notification_answer!(current_user, answer_id, visited_id)
        notification = current_user.active_notifications.new(
            post_id: id,
            answer_id: answer_id,
            visited_id: user_id,
            action: 'answer'
        )
        notification.save if notification.valid?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page])
  end

  def answered
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page])
  end

  def show
    @answer = Answer.new
  end

  def new
    @post = Post.new
    @tags = Tag.all
  end

  def edit
    @tags = Tag.all
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      @post.user_id = current_user.id
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    @user = current_user.id
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:video, :content, :user_id, :best_answer_id, {:tag_ids => []})
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="btn-group btn-group-vertical" data-toggle="buttons">
    <div class="btn active">
      <% @tags.each do |tag| %>
        <%= form.label tag.name %><i class="fa fa-square-o fa-2x"></i><i class="fa fa-check-square-o fa-2x"></i>
        <%= radio_button_tag "post[tag_ids][]", tag.id, @post.tags.include?(tag) %>
      <% end %>
    </div>
  </div>

  <div class="box-video">
    <span><%= form.label :video, "動画ファイルを選択" %></span>
    <%= form.file_field :video, style: "display: none;" %>
  </div>

  <div class="content">
    <%= form.label :content, "コメント" %>
    <%= form.text_area :content %>
  </div>

  <div class="box-signup">
    <%= form.submit "投稿" %>
  </div>
<% end %>

app/views/posts/answered.html.erb
<dl class="searchbox">
  <%= search_form_for @q, url: posts_answered_path do |f| %>
    <dt><%= f.search_field :content_or_user_username_or_tags_name_cont %></dt>
    <dd><%= f.submit "検索", class: 'search-btn' %></dd>
  <% end %>
</dl>

<div class="answers">
  <%= link_to(posts_path) do %>
    <button class="btn btn--orange btn--cubic btn--shadow">未解決一覧へ</button>
  <% end %>
</div>

<h1 class="posts">みんなの投稿</h1>

<table>
    <tr>
      <th>種目</th>
      <th>動画</th>
      <th>コメント</th>
      <th>投稿者</th>
    </tr>

  <div class="scroll-list jscroll">
      <tr>
        <% @posts.each do |post| %>
          <% if post.best_answer_id %>
            <td class="icon"><% post.tags.each do |tag| %>
              <%= tag.name %></td>
            <% end %>
            <td class="icon">
                <%= link_to post.video_url.to_s do %>
                  <%= video_tag(post.video.to_s, :controls => true, :size => 15*10) %>
                <% end %>
            </td>
            <td class="icon"><%= post.content %>
            <p><%= time_ago_in_words(post.created_at) %>前</p>
            </td>
            <td class="icon"><%= link_to post.user.username, user_path(post.user) %>
              <p><%= link_to '見てみる', post_path(post) %></p>
            <div class="icon" id="post_<%= post.id %>">
              <p><%= render partial: "likes/like", locals: {post: post} %></p>
            </td>
      </tr>
        <% end %>
    <% end %>
</table>
  <%= paginate @posts %>
</div>

<div class="hoge">
</div>

app/views/posts/edit.html.erb
<div class="box-post-edit">
    <div class="box-inner">
        <h1>変更</h1>
        <%= render 'form', post: @post %>
    </div>
</div>

<div class="show">
    <%= link_to(@post) do %>
        <p class="btn btn--orange btn-primate">詳細</p>
    <% end %>
</div>

<div class="back">
    <%= link_to(user_path(current_user.id)) do %>
        <p class="btn btn--orange btn-primary">戻る</p>
    <% end %>
</div>

app/views/posts/index.html.erb
<dl class="searchbox">
  <%= search_form_for @q, url: posts_path do |f| %>
    <dt><%= f.search_field :content_or_user_username_or_tags_name_cont %></dt>
    <dd><%= f.submit "検索", class: 'search-btn' %></dd>
  <% end %>
</dl>

<div class="answers">
  <%= link_to(posts_answered_path) do %>
    <button class="btn btn--orange btn--cubic btn--shadow">回答済み一覧へ</button>
  <% end %>
</div>

<h1 class="posts">みんなの投稿</h1>

<table>
  <tr>
    <th>種目</th>
    <th>動画</th>
    <th>コメント</th>
    <th>投稿者</th>
  </tr>

  <div class="scroll-list jscroll">
    <tr>
      <% @posts.each do |post| %>
      <% if post.best_answer_id == nil %>
          <td class="icon"><% post.tags.each do |tag| %>
            <%= tag.name %>
          </td>
          <% end %>
          <td class="icon">
              <%= link_to post.video_url.to_s do %>
                <%= video_tag(post.video.to_s, :controls => true, :size => 15*10) %>
              <% end %>
          </td>
          <td class="icon"><%= post.content %>
            <p><%= time_ago_in_words(post.created_at) %>前</p>
          </td>
          <td class="icon"><%= link_to post.user.username, user_path(post.user) %>
            <p><%= link_to '見てみる', post_path(post) %></p>
          <div class="icon" id="post_<%= post.id %>">
            <p><%= render partial: "likes/like", locals: {post: post} %></p>
          </td>
    </tr>
      <% end %>
  <% end %>
</table>
    <%= paginate @posts %>
  </div>

<div class="hoge">
</div>

app/views/posts/new.html.erb
<div class="box-post">
    <div class="box-inner">

        <h1>新規投稿</h1>

        <%= render 'form', post: @post %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="post-show">
  <table class="row">
    <tr><th>種目</th>
      <% @post.tags.each do |tag| %>
        <td><%= tag.name %></td></tr>
      <% end %>

    <tr><th>動画</th>
      <%= link_to @post.video_url.to_s do %>
        <td><%= video_tag(@post.video.to_s, :controls => true, :size => 25*15) %></td></tr>
      <% end %>

    <tr><th>コメント</th>
    <td><%= @post.content %></td></tr>

      <tr><th>お気に入り</th>
        <p id="favorite_<%= @post.id %>">
          <td><%= render partial: 'favorites/favorite', locals: {post: @post} %></tr></td>
        </p>
  </table>
</div>

<% if @post.answers.any? %>
  <div class="answer">
    <h1>みんなの回答</h1>
  </div>
  <p class="border">---------------------------------------------------------------------</p>
  <% @post.answers.each do |answer| %>
    <div class="ba">
      <button class="best"><%= 'ベストアンサー' if @post.best_answer_id == answer.id %></button>
    </div>
    <p class="answer-name"><%= answer.answer_name %>さんの回答</p>
    <p class="answer-content"><%= answer.content %><p>
    <p class="answer-time"><%= time_ago_in_words(answer.created_at) %>前</p>
    <div class="reaction">
       <%= link_to(new_answer_reaction_path(answer.id)) do %>
      <button class="btn btn--orange btn--cubic btn--shadow">反応する</button>
      <% end %>
    <% if @post.user_id == current_user.id %>
      <%= form_with(model: @post, local: true, data: {confirm: "#{answer.answer_name}さんの回答をベストアンサーにします"}) do |f| %>
        <%= f.hidden_field :best_answer_id, value: answer.id %>
        <%= f.submit 'ベストアンサーに選ぶ', disabled: @post.best_answer_id.present? %>
      <% end %>
    </div>
    <% end %>

    <p class="border">---------------------------------------------------------------------</p>
    <% answer.reactions.each do |reaction| %>
      <p class="answer-name"><%= reaction.user.username %>さんの反応</p>
      <p class="answer-content"><%= reaction.body %></p>
      <p class="answer-time"><%= time_ago_in_words(reaction.created_at) %>前</p>
    <div class="reaction">
         <%= link_to(new_answer_reaction_path(answer.id)) do %>
          <button class="btn btn--orange btn--cubic btn--shadow">反応する</button>
    </div>
          <% end %>
      <p class="border">---------------------------------------------------------------------</p>
      <% end %>
    <% end %>
<% else %>
  <div class="not-answer">
    <h1>回答がありません</h1>
  </div>
<% end %>

<% if @post.user.id != current_user.id %>
  <h1 class="true">回答</h1>
  <%= form_with model: [@post, @answer], local: true do |f| %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :answer_name, value: current_user.username %>
    <%= f.text_area :content, class: "answers-content" %>
    <div class="answer-btn">
      <%= f.submit "回答", class: "btn btn--orange btn--cubic btn--shadow" %>
    </div>
  <% end %>
<% end %>